# application.yml

# SPRING CONFIG
spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/automatch-dev
    username: postgres
    password: 06823420
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# JWT CONFIG (fora do spring)
jwt:
  secret-key: "mySuperSecretKeyThatIsAtLeast32BytesLong1234567890"
  expiration-hours: 24

# SERVER CONFIG
server:
  port: 8080