name: Deploy Backend Spring

on:
  push:
    branches:
      - mains

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Java 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build do Spring
        run: mvn clean package -DskipTests

      - name: Auth no Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy no Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: demo-backend
          region: us-central1
          source: .
